---
title: "The Epidemic of Microtransactions on Mobile Gaming"
subtitle: "Brandon's Data Science Portfolio"
output:
  html_document:
    df_print: paged
---

## Abstract

From virtual currency to in-app purchases, microtransactions are a huge aspect of modern gaming. Looking at apple store data from 2017, I am trying to discover potential causes and effects of microtransactions. Is there a reason besides money for this "epidemic" of microtransactions or is it all for monetary gain? This project is going to dive into the specifics of age rating, app prices, app ratings, and genres all for the ultimate goal to answer why microtransactions are so important in modern gaming.

### 1. Discovery and Data Preparation

This file introduces the data, goes through data cleaning and creating tibbles ultimately leading to my research questions based on age rating of the apps.

https://introdsci.github.io/DataScience-bnleff/deliverable1.html

### 2. Model Planning and Building

This file introduces a new dataset, cleans the new data set, creates a new model in R and then follows up the model in R with python work and visualizations. This file dives deeper into the question of how content rating is involved in app ratings.

https://introdsci.github.io/DataScience-bnleff/deliverable2.html

### 3. Results and Operationalization

Coming soon...

